[package]
name = "hebrewsky"
version = "0.1.0"
edition = "2021"
default-run = "hebrewsky"

[[bin]]
name = "publish-feed"

[dependencies]
axum = { version = "0.7.5", features = ["http2", "tracing", "ws"] }
futures = "0.3.30"
tokio = { version = "1.40.0", features = ["full"] }
tracing = "0.1.40"
serde_cbor = "0.11.2"
serde = { version = "1.0.209", features = ["derive"] }
sqlx = { version = "0.8.2", features = ["runtime-tokio", "sqlite"] }
fastwebsockets = { version = "0.8.0", features = ["upgrade"] }
hyper = { version = "1.4.1", features = ["full"] }
reqwest = { version = "0.12.7", default-features = false, features = [
    "http2",
    "rustls-tls-webpki-roots",
    "brotli",
    "zstd",
    "deflate",
    "gzip",
    "json",
    "rustls-tls",
] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
atrium-api = "0.24.2"
ciborium = "0.2.2"
serde_ipld_dagcbor = "0.6.1"
cid = "0.11.1"
console-subscriber = "0.4.0"
flume = "0.11.0"
dotenvy = "0.15.7"
tower-http = { version = "0.5.2", features = [
    "compression-br",
    "compression-deflate",
    "compression-gzip",
    "compression-zstd",
    "trace",
] }
ipld-core = "0.4.1"
bsky-sdk = "0.1.8"
axum-extra = { version = "0.9.3", features = ["typed-header"] }
rs-car = "0.4.1"
serde_json = "1.0.128"
atrium-crypto = "0.1.0"
base64 = "0.22.1"
whatlang = "0.16.4"
